### ISSUE TITLE
attributes appended by default

### ISSUE THREAD

**Issue by rainerborene** [nickdunn/form-controls#3]
Hello nick,

I have a question about this great tool. This utility appends the attributes `title` and `value` without any value by default? 

Here is my [template](http://pastie.org/644084). Check out the result [http://pastie.org/644087](http://pastie.org/644087).

If the value wasn't defined it's not necessary to append these attributes, right?

Thanks in advance!

**Comment by nickdunn** [comment]
> If the value wasn't defined it's not necessary to append these attributes, right?

Right. Unfortunately I am using `xsl:attribute-sets` to add the generic sets of attributes that are common to all controls. When using attribute sets XSLT assumes that all attributes should always be added even when no value is specified. This is what the `value` and `title` attributes are added with blank values when you specify no value.

Originally I had separate `xsl:call-templates` for each attribute but this felt very messy and increased code size by many, many lines. Using attribute-sets is the most elegant solution since it is using a powerful feature of the XSLT language. But having the blank attributes is an unfortunate side effect.
